using System.Collections.Generic;
using System.IO;
using System.Text;
using Plunderspell.Castle;
using Plunderspell.Loot;
using Plunderspell.Raid;
using UnityEditor;
using UnityEngine;

namespace Plunderspell.EditorTools
{
    /// <summary>
    /// Walks generated castles the way a player would and reports what is broken (castle revamp,
    /// phase 1 — docs/plans/castle-revamp.md). Run in Play mode in a scene with a RaidDirector
    /// (CastleBench): for each seed it builds the castle, then checks on the castle's nav graph that every
    /// room and every piece of loot can be walked to from the spawn, and that no loot sits outside a
    /// room or inside the geometry.
    /// </summary>
    public static class CastleAudit
    {
        public const string ReportFolder = "docs/generated/castle-survey-2026-09-23";
        // Probe radii, metres, in the graph's 3D distance. They are the old NavMesh.SamplePosition radii
        // (3, 0.5 and 1.6); the graph measures to a cell centre, which sits up to half a cell from the edge.
        private const float k_spawnRadius = 3f;
        private const float k_floorProbeRadius = 0.5f;
        private const float k_lootProbeRadius = 1.6f;
        private static readonly int[] s_defaultSeeds = { 12345, 777, 2024, 31337, 90210 };

        [MenuItem("Tools/Plunderspell/Audit Castle Navigation (Play mode)")]
        public static void RunDefault() => Run(s_defaultSeeds, "latest");

        /// <summary>One floor sample from the last run, for drawing the overlay.</summary>
        public struct Probe
        {
            public Vector3 World;
            public bool Walkable;
            public bool Reached;
        }

        private static readonly List<Probe> s_points = new List<Probe>();

        /// <summary>Floor samples from the most recent seed audited (the last in the list).</summary>
        public static IReadOnlyList<Probe> LastProbes => s_points;

        /// <summary>Audits each seed and writes a Markdown report. Returns the report text.</summary>
        public static string Run(int[] seeds, string label)
        {
            if (!Application.isPlaying)
            {
                Debug.LogWarning("[CastleAudit] Enter Play mode in CastleBench first; the audit needs a live castle.");
                return "not playing";
            }

            var director = Object.FindAnyObjectByType<RaidDirector>();
            var loot = Object.FindAnyObjectByType<LootSpawner>();
            var guards = Object.FindAnyObjectByType<GuardSpawner>();
            var player = Object.FindAnyObjectByType<StateMachine.PlayerStateMachine>();
            if (director == null || player == null)
            {
                Debug.LogWarning("[CastleAudit] No RaidDirector or player in this scene.");
                return "no director";
            }

            var report = new StringBuilder();
            report.AppendLine($"# Castle navigation audit: {label}");
            report.AppendLine();
            report.AppendLine("Generated by `Tools/Plunderspell/Audit Castle Navigation` (`CastleAudit.cs`). Rooms and loot");
            report.AppendLine("are checked on the castle's nav graph (#223), reachable from the player's spawn.");
            report.AppendLine();
            report.AppendLine("| Seed | Rooms | Rooms you cannot enter | Floor reachable | Loot | Loot unreachable | Loot outside a room | Loot inside geometry |");
            report.AppendLine("|---|---|---|---|---|---|---|---|");

            var details = new StringBuilder();
            int totalBadRooms = 0, totalBadLoot = 0;

            foreach (int seed in seeds)
            {
                loot?.Clear();
                guards?.Clear();
                s_points.Clear();
                ProceduralCastleData castle = director.BuildCastle(seed);
                if (castle == null)
                    continue;
                Physics.SyncTransforms();

                Vector3 spawn = player.transform.position;
                CastleNavGraph graph = castle.NavGraph;
                int spawnCell = graph != null ? graph.NearestWalkableCell(spawn, k_spawnRadius) : CastleNavGrid.NoCell;
                bool spawnOnGraph = spawnCell != CastleNavGrid.NoCell;

                var cells = new Dictionary<Vector2Int, ProceduralCastleData.PlacedModule>();
                foreach (var m in castle.PlacedModules)
                    cells[m.GridPosition] = m;

                // A room counts as reachable only by its floor: 25 sample points on a grid across the
                // room at floor height. Sampling the centre alone snapped onto prop tops (a table is
                // walkable too, just not one you can walk onto) and misreported every furnished room.
                int rooms = 0, badRooms = 0, floorPoints = 0, floorReached = 0;
                foreach (var m in castle.PlacedModules)
                {
                    if (!ProceduralCastleGenerator.IsEnclosedRoom(m.Zone))
                        continue;
                    rooms++;
                    int reached = 0, onFloor = 0;
                    for (int gx = -2; gx <= 2; gx++)
                    {
                        for (int gz = -2; gz <= 2; gz++)
                        {
                            Vector3 probe = m.Position + new Vector3(gx * 2.2f, 0.35f, gz * 2.2f);
                            int cell = graph != null ? graph.NearestWalkableCell(probe, k_floorProbeRadius) : CastleNavGrid.NoCell;
                            bool floor = cell != CastleNavGrid.NoCell && graph.CellPosition(cell).y < 0.55f;
                            bool ok = floor && spawnOnGraph && graph.IsReachable(spawnCell, cell);
                            if (floor) onFloor++;
                            if (ok) reached++;
                            s_points.Add(new Probe { World = probe, Walkable = floor, Reached = ok });
                        }
                    }
                    floorPoints += onFloor;
                    floorReached += reached;
                    if (reached == 0)
                    {
                        badRooms++;
                        details.AppendLine($"- seed {seed}: room **{m.RoomId}** at {m.GridPosition}: none of its floor can be walked to.");
                    }
                    else if (reached < onFloor)
                    {
                        details.AppendLine($"- seed {seed}: room **{m.RoomId}** at {m.GridPosition}: only {reached}/{onFloor} floor points can be walked to.");
                    }
                }

                int pieces = 0, unreachable = 0, outside = 0, embedded = 0;
                if (loot != null)
                {
                    foreach (GameObject piece in loot.Spawned)
                    {
                        if (piece == null)
                            continue;
                        pieces++;
                        Vector3 p = piece.transform.position;
                        var moduleCell = new Vector2Int(Mathf.RoundToInt(p.x / 12f), Mathf.RoundToInt(p.z / 12f));
                        string room = cells.TryGetValue(moduleCell, out var inRoom) ? inRoom.RoomId : "no module";

                        if (!cells.TryGetValue(moduleCell, out var at) || !ProceduralCastleGenerator.IsEnclosedRoom(at.Zone))
                        {
                            outside++;
                            details.AppendLine($"- seed {seed}: {piece.name} at {p:F1} is not inside a room ({room}).");
                        }

                        bool reach = spawnOnGraph && CanReach(graph, spawnCell, p);
                        if (!reach)
                        {
                            unreachable++;
                            details.AppendLine($"- seed {seed}: {piece.name} at {p:F1} in {room} cannot be walked to.");
                        }

                        if (IsInsideGeometry(piece))
                        {
                            embedded++;
                            details.AppendLine($"- seed {seed}: {piece.name} at {p:F1} in {room} is inside castle geometry.");
                        }
                    }
                }

                totalBadRooms += badRooms;
                totalBadLoot += unreachable + outside + embedded;
                float floorShare = floorPoints == 0 ? 0f : 100f * floorReached / floorPoints;
                report.AppendLine($"| {seed} | {rooms} | {badRooms} | {floorShare:0}% | {pieces} | {unreachable} | {outside} | {embedded} |");
            }

            report.AppendLine();
            report.AppendLine(totalBadRooms + totalBadLoot == 0 ? "**No problems found.**" : "## Problems");
            report.AppendLine();
            report.Append(details);

            string file = Path.Combine(ReportFolder, $"audit-{label}.md");
            Directory.CreateDirectory(ReportFolder);
            File.WriteAllText(file, report.ToString());
            Debug.Log($"[CastleAudit] {totalBadRooms} unreachable rooms, {totalBadLoot} loot problems. Report: {file}");
            return report.ToString();
        }

        /// <summary>
        /// Can a player stand within arm's reach of this piece? Loot sits on table tops and shelves,
        /// which the old NavMesh gave their own little patch of walkable ground; checking the patch nearest
        /// the piece asked whether you could stand ON the table. This asks for a graph cell within 1.6 m
        /// across and up to 1.6 m below the piece that the spawn can reach.
        /// </summary>
        private static bool CanReach(CastleNavGraph graph, int spawnCell, Vector3 loot)
        {
            foreach (float drop in new[] { 0f, 0.8f, 1.4f })
            {
                int cell = graph.NearestWalkableCell(loot + Vector3.down * drop, k_lootProbeRadius);
                if (cell == CastleNavGrid.NoCell)
                    continue;
                Vector3 d = graph.CellPosition(cell) - loot;
                if (new Vector2(d.x, d.z).magnitude > 1.6f || d.y > 0.3f || d.y < -1.8f)
                    continue;
                if (graph.IsReachable(spawnCell, cell))
                    return true;
            }
            return false;
        }

        /// <summary>True when the piece overlaps solid castle geometry (not other loot, not triggers).</summary>
        private static bool IsInsideGeometry(GameObject piece)
        {
            var own = piece.GetComponentInChildren<Collider>();
            if (own == null)
                return false;
            Bounds b = own.bounds;
            Collider[] hits = Physics.OverlapBox(b.center, b.extents * 0.8f, Quaternion.identity, ~0, QueryTriggerInteraction.Ignore);
            foreach (Collider hit in hits)
            {
                if (hit.transform.IsChildOf(piece.transform))
                    continue;
                if (hit.GetComponentInParent<LootValue>() != null || hit.attachedRigidbody != null)
                    continue;
                return true;
            }
            return false;
        }
    }
}
