using System.IO;
using System.Linq;
using System.Reflection;
using System.Text.RegularExpressions;
using NUnit.Framework;
using Player;
using Plunderspell.EditorTools;
using UnityEditor.Animations;
using UnityEngine;

namespace Plunderspell.Tests.Editor
{
    /// <summary>The wizard's import rules and its animation driver (#361, #362).</summary>
    public class WizardAnimationTests
    {
        private const string PlayerManifest = "Assets/Models/ArtBible/Animations/player_anim_manifest.json";

        [Test]
        public void ImporterClassifiesTheWizardAndItsClips()
        {
            Assert.AreEqual(ArtBibleModelImporter.Kind.HumanoidPlayer,
                ArtBibleModelImporter.KindOf("Assets/Models/ArtBible/Players/Lair/Wizard/Wizard.fbx"));
            Assert.AreEqual(ArtBibleModelImporter.Kind.HumanoidClips,
                ArtBibleModelImporter.KindOf(ArtBibleModelImporter.PlayerClipsPath));
            Assert.IsNull(ArtBibleModelImporter.KindOf("Assets/Models/ArtBible/Players/Lair/Wizard/Wizard.blend"));
        }

        [Test]
        public void LoopFlagsMatchTheClipManifest()
        {
            string path = Path.GetFullPath(Path.Combine(Application.dataPath, "..", PlayerManifest));
            Assert.IsTrue(File.Exists(path), $"{PlayerManifest} missing: run Tools/ArtForge/anim_player.py build");
            string json = File.ReadAllText(path);

            // Flat, generated by our own script: "clip": "<id>", ... "loop": true|false.
            var looping = Regex.Matches(json, "\"clip\":\\s*\"([^\"]+)\"[^{}]*?\"loop\":\\s*(true|false)")
                .Cast<Match>()
                .Where(m => m.Groups[2].Value == "true")
                .Select(m => m.Groups[1].Value)
                .OrderBy(id => id)
                .ToArray();
            CollectionAssert.AreEqual(ArtBibleModelImporter.LoopingPlayerClips.OrderBy(id => id).ToArray(), looping,
                "ArtBibleModelImporter.LoopingPlayerClips must list exactly the looping clips in the manifest");
        }

        [Test]
        public void RemoteFlagsDriveTheAnimator()
        {
            (WizardAnimationDriver driver, Animator animator) = MakeWizard();
            driver.IsRemote = true;
            driver.RemoteCreeping = true;
            driver.RemoteCasting = true;
            Tick(driver);
            Assert.IsTrue(animator.GetBool("Crouch"));
            Assert.IsTrue(animator.GetBool("Casting"));
            Assert.IsFalse(animator.GetBool("Dead"));
        }

        [Test]
        public void ADownedWizardStopsCastingAndJumping()
        {
            (WizardAnimationDriver driver, Animator animator) = MakeWizard();
            driver.IsRemote = true;
            driver.RemoteCasting = true;
            driver.RemoteAirborne = true;
            driver.RemoteDown = true;
            Tick(driver);
            Assert.IsTrue(animator.GetBool("Dead"));
            Assert.IsFalse(animator.GetBool("Casting"), "a fallen wizard keeps casting");
            Assert.IsFalse(animator.GetBool("Airborne"), "a fallen wizard keeps jumping");
        }

        private static (WizardAnimationDriver, Animator) MakeWizard()
        {
            var root = new GameObject("Player");
            var model = new GameObject("Wizard");
            model.transform.SetParent(root.transform, false);
            Animator animator = model.AddComponent<Animator>();
            // The Animator keeps parameter values only with a controller that has a layer, once bound;
            // otherwise SetBool is dropped and GetBool reads false.
            var controller = new AnimatorController();
            controller.AddLayer("Base Layer");
            controller.AddParameter("Speed", AnimatorControllerParameterType.Float);
            foreach (string flag in new[] { "Crouch", "Airborne", "Casting", "Dead" })
                controller.AddParameter(flag, AnimatorControllerParameterType.Bool);
            animator.runtimeAnimatorController = controller;
            animator.Rebind();
            WizardAnimationDriver driver = root.AddComponent<WizardAnimationDriver>();
            Invoke(driver, "Awake");
            return (driver, animator);
        }

        private static void Tick(WizardAnimationDriver driver) => Invoke(driver, "Update");

        private static void Invoke(WizardAnimationDriver driver, string method) =>
            typeof(WizardAnimationDriver).GetMethod(method, BindingFlags.NonPublic | BindingFlags.Instance)
                .Invoke(driver, null);
    }
}
