using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Audio;

namespace Plunderspell.Audio
{
    /// <summary>How loud a sound is to the guards, from the manifest's noise column.</summary>
    public enum SoundNoise
    {
        None = 0,
        Low = 1,
        Mid = 2,
        High = 3,
        Max = 4
    }

    /// <summary>One sound: its variants and how it plays. Generated from the manifest by the editor.</summary>
    [Serializable]
    public sealed class SoundEntry
    {
        public string Name;
        public AudioClip[] Clips = Array.Empty<AudioClip>();
        public AudioMixerGroup Group;
        public bool ThreeD;
        public bool Loop;
        public SoundNoise Noise;
        public float Volume = 1f;

        /// <summary>Random pitch nudge either side of 1, so a repeated sound does not repeat exactly.</summary>
        public float PitchRange = 0.05f;
    }

    /// <summary>
    /// Every sound the game can play, keyed by manifest name. Generated by
    /// <c>Plunderspell &gt; Audio &gt; Rebuild SoundBank</c>; never edit an entry by hand.
    /// See docs/4-systems/audio.md.
    /// </summary>
    public sealed class SoundBank : ScriptableObject
    {
        [SerializeField] private AudioMixer _mixer;
        [SerializeField] private List<SoundEntry> _entries = new List<SoundEntry>();

        private Dictionary<string, SoundEntry> _lookup;

        public AudioMixer Mixer => _mixer;
        public IReadOnlyList<SoundEntry> Entries => _entries;

        public bool TryGet(string soundName, out SoundEntry entry)
        {
            if (_lookup == null || _lookup.Count != _entries.Count)
            {
                _lookup = new Dictionary<string, SoundEntry>(_entries.Count);
                for (int i = 0; i < _entries.Count; i++)
                    _lookup[_entries[i].Name] = _entries[i];
            }

            if (soundName != null && _lookup.TryGetValue(soundName, out entry))
                return true;
            entry = null;
            return false;
        }

        /// <summary>Editor seam: replaces the contents. Called only by the rebuild command.</summary>
        public void Assign(AudioMixer mixer, List<SoundEntry> entries)
        {
            _mixer = mixer;
            _entries = entries;
            _lookup = null;
        }
    }
}
