"""Builds the guard-voice recording script and the recorder page.

One person records ONE set of lines per Age; the game disguises that set into many guards later.
The line text is NOT copied here: it is imported from Tools/AudioForge/vo/make_line_sheets.py.

    python Tools/GuardVoice/make_recording_script.py

Writes (deterministically, same input gives the same bytes):
    Tools/GuardVoice/recording-script/<age>.md
    Tools/GuardVoice/record-lines.json
    Tools/GuardVoice/record.html   (from record.template.html, JSON embedded so file:// works)
"""

import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
VO_DIR = HERE.parent / "AudioForge" / "vo"
sys.path.insert(0, str(VO_DIR))
from make_line_sheets import AGES, DIRECTION  # noqa: E402  (path set up just above)

# situation -> (tone, loudness, minimum take seconds)
TONES = {
    "murmur": ("Half to yourself, bored and unhurried, low energy.", "quiet", 1.5),
    "alert": ("Suspicious and sharp. Let a question rise at the end.", "normal", 0.6),
    "chase": ("SHOUTED, urgent, from the gut, full volume.", "loud", 0.8),
    "search": ("Slow and low, playful menace. Stretch the vowels.", "normal", 1.2),
    "lost": ("Deflated and a bit embarrassed. Pitch drops at the end.", "quiet", 1.0),
    "attack": ("Short explosive effort sound, from the chest.", "loud", 0.3),
    "hurt": ("Sharp and short, surprised pain, not gory. Normal to loud.", "normal", 0.3),
    "death": ("Theatrical and a little comic, fading out. Never gory.", "normal", 0.8),
    "asleep": ("Slow deep snoring, three full breaths, at least 6 seconds.", "quiet", 6.0),
    "grabbed": ("Indignant outrage, squeaky at the top.", "loud", 0.6),
    "thrown": ("A long falling scream that starts loud and trails off.", "loud", 1.5),
}

LEADING_DIRECTION = re.compile(r"^\*\(([^)]*)\)\*\s*")
TRAILING_TRANSLATION = re.compile(r"\s*\*\(([^)]*)\)\*\s*$")


def split_line(raw):
    """Return (spoken text, stage direction, translation note) for one sheet line.

    A leading *(...)* is a stage direction. A trailing *(...)* after spoken words is a
    translation: shown as a note, never spoken.
    """
    text = raw
    direction = ""
    translation = ""
    m = LEADING_DIRECTION.match(text)
    if m:
        direction = m.group(1)
        text = text[m.end():]
    m = TRAILING_TRANSLATION.search(text)
    if m:
        translation = m.group(1)
        text = text[:m.start()]
    return text.strip(), direction, translation


def build_line(age, situation, number, raw):
    text, direction, translation = split_line(raw)
    tone, loudness, min_seconds = TONES[situation]
    lowered = direction.lower()
    if direction:
        tone = f"{tone} Direction for this line: {direction}."
    if "quietly" in lowered:
        loudness = "quiet"
        tone = "Hushed and suspicious. " + tone
    if "hum" in lowered:
        min_seconds = 4.0
    note_parts = []
    if translation:
        note_parts.append(f"Means: {translation.rstrip('.!?')}. Do not say this part.")
    if not text:
        note_parts.append("No words: just make the sound described.")
    return {
        "age": age,
        "situation": situation,
        "number": number,
        "file": f"vo_{age}_base_{situation}_{number:02d}.wav",
        "text": text,
        "direction": direction,
        "tone": tone,
        "loudness": loudness,
        "minSeconds": min_seconds,
        "note": " ".join(note_parts),
    }


def age_voice_line(spec):
    """One-line 'how to sound': the first voice's character, markdown emphasis stripped."""
    first = next(iter(spec["voices"].values()))
    return first.replace("**", "").replace("*", "")


def write_markdown(age, spec, lines, out_dir):
    md = [f"# Recording script: {spec['title']}", "",
          "*Generated by `Tools/GuardVoice/make_recording_script.py`; edit the lines in "
          "`Tools/AudioForge/vo/make_line_sheets.py`, not here.*", "",
          f"**How to sound:** {age_voice_line(spec)}", "",
          "One person reads ALL the lines below in ONE voice. Do not do different characters; "
          "the game disguises this one voice into many guards later.", "",
          f"**Language:** {spec['language'].replace('*', '')}", "",
          "**Mic gain:** turn it DOWN before any line marked loud (shouts distort), "
          "and back up for quiet lines.", "",
          f"**Save to:** `Tools/GuardVoice/takes/{age}/` (choose this folder in the recorder page).", ""]
    current = None
    for ln in lines:
        if ln["situation"] != current:
            current = ln["situation"]
            tone, loudness, _ = TONES[current]
            md += [f"## {current} ({DIRECTION[current]})", "", f"Tone: {tone} Loudness: {loudness}.", ""]
        spoken = ln["text"] if ln["text"] else "(no words)"
        md.append(f"- `{ln['file']}` ({ln['loudness']}, at least {ln['minSeconds']:g} s): {spoken}")
        if ln["direction"]:
            md.append(f"  - Direction: {ln['direction']}")
        if ln["note"]:
            md.append(f"  - {ln['note']}")
    md.append("")
    (out_dir / f"{age}.md").write_text("\n".join(md), encoding="utf-8", newline="\n")


def main():
    out_dir = HERE / "recording-script"
    out_dir.mkdir(exist_ok=True)
    data = {"ages": []}
    total = 0
    for age, spec in AGES.items():
        lines = []
        for situation, raws in spec["lines"].items():
            for number, raw in enumerate(raws, 1):
                lines.append(build_line(age, situation, number, raw))
        total += len(lines)
        write_markdown(age, spec, lines, out_dir)
        data["ages"].append({
            "id": age,
            "title": spec["title"],
            "howToSound": age_voice_line(spec),
            "language": spec["language"].replace("*", ""),
            "lines": lines,
        })
    json_text = json.dumps(data, indent=1, ensure_ascii=False)
    (HERE / "record-lines.json").write_text(json_text + "\n", encoding="utf-8", newline="\n")

    template = (HERE / "record.template.html").read_text(encoding="utf-8")
    if "__LINES_JSON__" not in template:
        raise SystemExit("record.template.html has no __LINES_JSON__ placeholder")
    # "</" inside a script block could end it early, so escape it.
    embedded = json.dumps(data, ensure_ascii=False).replace("</", "<\\/")
    (HERE / "record.html").write_text(template.replace("__LINES_JSON__", embedded),
                                      encoding="utf-8", newline="\n")
    counts = ", ".join(f"{a['id']}={len(a['lines'])}" for a in data["ages"])
    print(f"wrote {len(data['ages'])} scripts, {total} lines ({counts})")
    print("sample file names:", data["ages"][0]["lines"][0]["file"], "and", data["ages"][3]["lines"][-1]["file"])


if __name__ == "__main__":
    main()
